# Generated by Django 6.0.4 on 2026-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('categoria', models.CharField(choices=[('alimentos', 'Alimentos'), ('outros', 'Outros'), ('roupas', 'Roupas e Acessórios'), ('livros', 'Livros'), ('eletronicos', 'Eletrônicos')], default='outros', max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('avaliacao', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendedores',
                'ordering': ['nome'],
            },
        ),
    ]
