# Generated by Django 6.0.4 on 2026-04-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_produto_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('outros', 'Outros'), ('alimentos', 'Alimentos'), ('livros', 'Livros'), ('roupas', 'Roupas e Acessórios')], default='outros', max_length=20),
        ),
    ]
